### ISSUE TITLE
BlockFertilizeEvent NPE

### ISSUE THREAD

**Issue by x1p** [MLG-Fortress/AutomaticInventory#41]
This error appears quite often nowadays.
I haven't figured out yet what player action produces this.
```
[11:26:46] [Server thread/ERROR]: Could not pass event BlockFertilizeEvent to AutomaticInventory v2.12.2-eab34e8
java.lang.NullPointerException: null
	at me.ryanhamshire.AutomaticInventory.AIEventHandler.onFertilize(AIEventHandler.java:74) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor186.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1086]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1086]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1086]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.IDispenseBehavior$19.a(IDispenseBehavior.java:743) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:25) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.BlockDispenser.dispense(BlockDispenser.java:93) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.BlockDispenser.tickAlways(BlockDispenser.java:119) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:676) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:1477) ~[patched_1.16.5.jar:git-Purpur-1086]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:309) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:59) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1064) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1563) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:433) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1086]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

AutomaticInventory v2.12.2
Purpur 1.16.5 (paper fork)

**Comment by RoboMWM** [comment]
https://github.com/MLG-Fortress/AutomaticInventory/blob/ea7cefec6111981042f26e2d2402d2e62fe18f14/src/me/ryanhamshire/AutomaticInventory/AIEventHandler.java#L71-L74

Looks like it's being caused by a dispenser which is not a player. Other than logspam this won't cause any in-game issues. This is an easy fix.

**Comment by ghost** [comment]
Could you please push and update for the plugin, it's been so long now. (May be fixed but got a report barrels don't autosort.)
