### ISSUE TITLE
Cannot invoke "org.bukkit.entity.Player.getInventory()" because "player" is null

### ISSUE THREAD

**Issue by Numpty-Clodpole** [MLG-Fortress/AutomaticInventory#47]
**Edit:**

*Oh.* Looks like it was fixed last year via #41, but hasn't been officially released. I guess I'll look into compiling the jarfile myself, sorry for being a bother.

**Edit2:**

![image](https://user-images.githubusercontent.com/19168008/171053521-98f5b82c-b356-4675-9753-a1520016cb51.png)

Compiled successfully, and it does function on the server. Now I guess it's a waiting game to see if I ever see that, or another error again.

______

There appears to something causing near-endless console spam, and I'm unable to verify why it happens or what ingame actions make it happen. This single error is spammed endlessly:

```
[19:47:20] [Server thread/ERROR]: Could not pass event BlockFertilizeEvent to AutomaticInventory v2.12.2-eab34e8
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getInventory()" because "player" is null
	at me.ryanhamshire.AutomaticInventory.AIEventHandler.onFertilize(AIEventHandler.java:74) ~[AutomaticInventory_2.12.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor48.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-351]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.core.dispenser.DispenseItemBehavior$19.execute(DispenseItemBehavior.java:830) ~[?:?]
	at net.minecraft.core.dispenser.DefaultDispenseItemBehavior.dispense(DefaultDispenseItemBehavior.java:32) ~[?:?]
	at net.minecraft.world.level.block.DispenserBlock.dispenseFrom(DispenserBlock.java:97) ~[?:?]
	at net.minecraft.world.level.block.DispenserBlock.tick(DispenserBlock.java:123) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1015) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1082) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:616) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-351]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-351]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-351]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-351]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-351]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The entire log, if wanted: https://paste.ee/p/6SFAI
I tried to use Pastebin, but the spam made it exceed their size limit. (I had no idea they even had a limit...)
![image](https://user-images.githubusercontent.com/19168008/171046039-fc6a33de-49a9-469c-b0cc-bb78cb6e38fa.png)

Just in case though, here's the log file as a direct upload to GitHub: [30-05-2022.log](https://github.com/MLG-Fortress/AutomaticInventory/files/8800215/30-05-2022.log)
 

Other information if needed/wanted:
* Paper 1.18.2, build 351
* AutomaticInventory 2.12.2 (your last upload to Bukkit was 20 December 2020)

Testing a spoiler function to prevent spam; click the text below to expand the rest:

<!DOCTYPE html>
<head>
<head>
</head>
<body>
<details>
<summary>Further details:</summary>

Fairly large plugin list: 
![image](https://user-images.githubusercontent.com/19168008/171046546-47cd296c-7c97-49df-a22c-5174e36ae0cd.png)

The potato system running the server: 
![image](https://user-images.githubusercontent.com/19168008/171049785-f62c02a6-ed22-4d14-add0-da54680c8740.png)

</details>
</body>
</html>

**Comment by RoboMWM** [comment]
I haven't pushed a release? Dang.
