### ISSUE TITLE
Error: Could not pass event BlockFertilizeEvent to AutomaticInventory

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#48]
If a grass block is shot with bonemeal by an underneath dispenser and plants grow as a result, the following error appears in the log:
```
> 2022-06-20 21:41:56,808 Server thread ERROR Recursive call to appender Async
[21:41:56 ERROR]: Could not pass event BlockFertilizeEvent to AutomaticInventory v2.12.2-eab34e8
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getInventory()" because "player" is null
        at me.ryanhamshire.AutomaticInventory.AIEventHandler.onFertilize(AIEventHandler.java:74) ~[AutomaticInventory.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.core.dispenser.DispenseItemBehavior$19.execute(DispenseItemBehavior.java:830) ~[?:?]
        at net.minecraft.core.dispenser.DefaultDispenseItemBehavior.dispense(DefaultDispenseItemBehavior.java:32) ~[?:?]
        at net.minecraft.world.level.block.DispenserBlock.dispenseFrom(DispenserBlock.java:97) ~[?:?]
        at net.minecraft.world.level.block.DispenserBlock.tick(DispenserBlock.java:123) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1015) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1082) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:616) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Since there are some farms based on this design, the error occurs very often in sequence. Therefore, it would be fantastic if you could fix the error.

![2022-06-20_21 54 34](https://user-images.githubusercontent.com/24480321/174673042-cfdb93cc-80e6-473e-b7b0-4afd293eb3e6.png)

Paper 1.18.2 build 384
AutomaticInventory version 2.12.2-eab34e8

**Comment by Momshroom** [comment]
Just compile it from the source.  It was fixed a long time ago, just not
released. :)

**Comment by RoboMWM** [comment]
Pushed a release finally. Think I meant to test automating releases with this project, but clearly I'm still nowhere close to that.
